sudo: true
language: ruby
install:
  # Use latest Augeas
  - sudo add-apt-repository -y ppa:raphink/augeas
  - sudo apt-get update
  - sudo apt-get install libaugeas-dev libxml2-dev
  # now, we can run
  - bundle install
before_script: 'bundle exec rake fixture:prepare'
script: 'SPEC_OPTS="--format documentation" bundle exec rake spec'
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
env:
  - PUPPET_GEM_VERSION="~> 2.7"
  - PUPPET_GEM_VERSION="~> 3.3"
  - PUPPET_GEM_VERSION="~> 3.7"
  - PUPPET_GEM_VERSION="~> 4"
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: 2.1
      env: PUPPET_GEM_VERSION="~> 2.7"
  fast_finish: true
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "DjiIx0gDrAUU176TA+7WxrEJ27D504Irrhx37dqxmR/GXEMX58swwwsdr3wlaklR7/LAVafsL98A0Ff+DtynAOYcFXkmJHc3ZObp4UDHqKot2mzL8rrzf+23cO8eiKW72sNKarn4wzSlR9OXjbAf/m68u+SBkRm+cWUUZhSgFiY="
  on:
    tags: true
    # all_branches are required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 2.1
